export const SET_GAMES = 'SET_GAMES'
export const ADD_GAME = 'ADD_GAME'
export const GAME_FETCH = 'GAME_FETCH'
export const UPDATE_GAME = 'UPDATE_GAME'
export const GAME_DELETED = 'GAME_DELETED'
//export const url = '//shenfeng1945.top/react-crud/build'
export const url = ''
